import { getTemplateDocDefinition } from './deliverySlipTemplate';
import { getOrderTemplateDocDefinition } from './orderTemplate';
import pdfFonts from "pdfmake/build/vfs_fonts";
import pdfMake from 'pdfmake/build/pdfmake';

//Mock data
const transportUnit = {
    "UpdatedAt": "2022-06-05T03:32:29.845Z",
    "Stage": 1001,
    "SenderAddress": "Fotostudio Vogelheim \n Hafenstr. 70 \n 45356 Essen",
    "PhotostudioID": "0979000",
    "KSUID": "24RxkZPEZQ8v2RM8F8hZxG8CRMo",
    "CreatedAt": "2022-01-31T05:35:43.179Z",
    "Name": "1710044579673693",
    "ReturnCenterID": "0000315",
    "ReturnCenterAddress": "Schreiberhauer Str. 55, 19317 Berlin, Germany",
    "Channel": "gkkCilGkkSapForward",
    "REPLICATION_PHOTOSTUDIO_UID": "0979000",
    "State": "ACTIVE",
    "ReturnCenterName": "Zuumeo",
    "ArticleTotal": 4
}

const articles = {
    "items": [
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "M-Jacken Wirk",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": true,
            "LatestTimestampUpdateType": "Dropped",
            "KSUID": "2DYHqTzntYlCyx74XZCplr0L6Tj",
            "InboundTimestamp": "2022-08-24T11:47:14.912Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "IsRequiredForModel": false,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|babyAndChildrensFashion|babyAndChildrensJackets",
            "DroppedTimestamp": "2022-08-24T12:00:03.640Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.560Z",
            "IssuedDate": "2022-07-30T00:06:48.082047+02:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-19T00:34:48.831Z",
            "UpdatedAt": "2022-08-24T12:01:02.561Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": true,
            "Gtin": "4099582179545",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 125,
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-19T00:34:48.891Z",
            "FMARequestID": "20220809_3RSARK",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "ConsumptionTopic": "400447",
            "ScannedAt": "2022-08-24T12:00:03.999Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "M-Gürtel/Hosenträger",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": true,
            "LatestTimestampUpdateType": "Dropped",
            "Size": "OneSize",
            "KSUID": "2DYHqTsjjhz09NwJXYrJPHXdWF3",
            "InboundTimestamp": "2022-08-24T11:47:22.459Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "TargetGroup": "Babys und Kleinkinder",
            "IsRequiredForModel": false,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|accessories|suspenders",
            "DroppedTimestamp": "2022-08-24T11:59:49.470Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.580Z",
            "IssuedDate": "2022-02-03T23:56:20.516655+01:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-19T00:34:48.806Z",
            "UpdatedAt": "2022-08-24T12:01:02.580Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": true,
            "Gtin": "4045782151843",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 140,
            "Title": "Kleinkind-Hosenträger, Länge ve, NAVY, 2",
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-19T00:34:48.836Z",
            "FMARequestID": "20220719_CVNKUF",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "BrandName": "GOL",
            "ConsumptionTopic": "400247",
            "Color": "NAVY",
            "ScannedAt": "2022-08-24T11:59:49.841Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "Plüschtiere, -fig.",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": false,
            "LatestTimestampUpdateType": "Dropped",
            "KSUID": "2DYHqGj5YJj1WlvV5GDWHku6AGd",
            "InboundTimestamp": "2022-08-24T11:49:39.666Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "TargetGroup": "Babys und Kleinkinder",
            "IsRequiredForModel": true,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "toysAndGames|dollsPuppetsAndCuddlyToys|plushToys",
            "DroppedTimestamp": "2022-08-24T11:56:52.645Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.583Z",
            "IssuedDate": "2022-02-03T22:52:42.672403+01:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-19T00:34:45.950Z",
            "UpdatedAt": "2022-08-24T12:01:02.583Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": true,
            "Gtin": "4001505080463",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 190,
            "Title": "Soft Cuddly Friends Kuscheltier Hase \"Hoppie\", 18 cm",
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-19T00:34:46.051Z",
            "FMARequestID": "20220706_X3WX4N",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "Description": "Ob gezielte Wunscherfüllung oder Überraschungsgeschenk. Kinderaugen leuchten, wenn Soft Cuddly Friends Hoppie Hase angehoppelt kommt. Es ist Liebe auf den ersten Blick! Der Hase mit seinen überlangen Ohren ist für Klein und Groß ein liebevoller Begleiter für jeden Tag. Mit ihm kann man tolle Verstecke und Höhlen bauen. Da ist Hoppie Hase Spezialist. Die eingearbeiteten Granulatsäckchen am Gesäß, den Pfoten und den Sohlen sorgen für einen sicheren Halt. Der weiche und dichte Plüsch in zartem Hellgrau lädt zum Anschmiegen und Liebhaben ein. Mit diesem Kuschelhasen kann man prima das Greifen und Tasten lernen. Und in den Ruhepausen legt Hoppie Hase seine überlangen Ohren über das Gesicht seines Menschenfreundes und flüstert ihm wunderschöne Einschlafgeschichten zu.",
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "BrandName": "Steiff",
            "ConsumptionTopic": "400068",
            "Color": "WEIß",
            "ScannedAt": "2022-08-24T11:56:53.198Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "BH's",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": true,
            "LatestTimestampUpdateType": "Dropped",
            "KSUID": "2DSdb6i8kX4r7Qr3UGoSpMquQBe",
            "InboundTimestamp": "2022-08-24T11:51:50.809Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "IsRequiredForModel": true,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|womensBras",
            "DroppedTimestamp": "2022-08-24T11:55:25.251Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.602Z",
            "IssuedDate": "2022-07-13T00:31:44.365042+02:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:47.178Z",
            "UpdatedAt": "2022-08-24T12:01:02.602Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": true,
            "Gtin": "4009602835894",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 125,
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:47.238Z",
            "FMARequestID": "20220803_XFDG5X",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "ConsumptionTopic": "400023",
            "ScannedAt": "2022-08-24T11:55:25.618Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "Mix + Match",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": true,
            "LatestTimestampUpdateType": "Dropped",
            "KSUID": "2DSdb5RaFfouvRXVg9tsxmv7dcc",
            "InboundTimestamp": "2022-08-24T11:48:20.035Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "IsRequiredForModel": false,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|unclassified",
            "DroppedTimestamp": "2022-08-24T11:58:52.647Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.621Z",
            "IssuedDate": "2022-05-11T21:51:44.774580+02:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:47.127Z",
            "UpdatedAt": "2022-08-24T12:01:02.621Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": false,
            "Gtin": "4009602856707",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 110,
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:47.162Z",
            "FMARequestID": "20220727_UGAV8L",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "ConsumptionTopic": "400020",
            "ScannedAt": "2022-08-24T11:58:52.952Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "Mix + Match",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": true,
            "LatestTimestampUpdateType": "Dropped",
            "KSUID": "2DSdb4nCo3bAcGjmtTgIE0sL43I",
            "InboundTimestamp": "2022-08-24T11:48:28.615Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "IsRequiredForModel": false,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|unclassified",
            "DroppedTimestamp": "2022-08-24T11:58:36.576Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.640Z",
            "IssuedDate": "2022-05-12T00:45:33.812661+02:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:47.197Z",
            "UpdatedAt": "2022-08-24T12:01:02.640Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": false,
            "Gtin": "4009602855793",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 110,
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:47.262Z",
            "FMARequestID": "20220805_KOWKQD",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "ConsumptionTopic": "400020",
            "ScannedAt": "2022-08-24T11:58:36.921Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "D-Nachthemden 1/2Arm",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": true,
            "LatestTimestampUpdateType": "Dropped",
            "KSUID": "2DSdb0LgYdNLAve0izQh1AiPZHG",
            "InboundTimestamp": "2022-08-24T11:47:59.305Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "IsRequiredForModel": false,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|unclassified",
            "DroppedTimestamp": "2022-08-24T11:59:08.132Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.643Z",
            "IssuedDate": "2022-05-11T22:57:30.906165+02:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:46.347Z",
            "UpdatedAt": "2022-08-24T12:01:02.643Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": false,
            "Gtin": "4009602856004",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 110,
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:46.400Z",
            "FMARequestID": "20220806_5JJMZJ",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "ConsumptionTopic": "400020",
            "ScannedAt": "2022-08-24T11:59:08.542Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "D-Bademäntel",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": false,
            "LatestTimestampUpdateType": "Dropped",
            "Size": "38",
            "KSUID": "2DSdayvMQwkr8OaX5VhCh36cyi5",
            "InboundTimestamp": "2022-08-24T11:47:34.479Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "TargetGroup": "Damen",
            "IsRequiredForModel": true,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|womensBathrobes",
            "DroppedTimestamp": "2022-08-24T11:59:36.410Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.661Z",
            "IssuedDate": "2022-02-03T21:02:34.757502+01:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:46.497Z",
            "UpdatedAt": "2022-08-24T12:01:02.662Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": true,
            "Gtin": "4007063814298",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 190,
            "Title": "Bademantel, uni, für Damen",
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:46.507Z",
            "FMARequestID": "20220712_3LL3T7",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "Description": "Lockerleicht Wohlfühlen: Dieser grau melierte Damenbademantel ist die perfekte Kombination aus feinem Design und gemütlichem Material. Ein dezenter Kragen, Taschen und das innere Bindeband schenken dem Bademantel dabei einen behaglichen Charakter, der sich im leichten Frottee Außen und mit glattem Material im Innenteil herrlich sanft und leicht auf der Haut anfühlt. Genau das Richtige für Damen, die es sich nach einem schönen Bad am liebsten in bester SCHIESSER-Qualität gemütlich machen.",
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "BrandName": "Schiesser",
            "ConsumptionTopic": "400020",
            "Color": "202 GRAU-MELANGE",
            "ScannedAt": "2022-08-24T11:59:36.774Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "D-Nachthemden 1/1Arm",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": true,
            "LatestTimestampUpdateType": "Dropped",
            "Size": "L",
            "KSUID": "2DSdaxbyLg7dfjGKoS62R5qMy4U",
            "InboundTimestamp": "2022-08-24T11:48:11.517Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "TargetGroup": "Damen",
            "IsRequiredForModel": true,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|womensNightgownsAndNegligees",
            "DroppedTimestamp": "2022-08-24T11:58:08.408Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.680Z",
            "IssuedDate": "2022-03-25T09:11:34.141389+01:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:46.379Z",
            "UpdatedAt": "2022-08-24T12:01:02.680Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": true,
            "Gtin": "4009602859005",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 130,
            "Title": "17439 Bigshirt 3/4 sleeve, 197  LILAC, L",
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:46.402Z",
            "FMARequestID": "20220810_UQ393T",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "BrandName": "Mey",
            "ConsumptionTopic": "400020",
            "Color": "197 LILAC",
            "ScannedAt": "2022-08-24T11:58:08.806Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "BH's",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": true,
            "LatestTimestampUpdateType": "Dropped",
            "KSUID": "2DSdawD8KhCrNlwzDIMp8zazzgd",
            "InboundTimestamp": "2022-08-24T11:48:57.659Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "IsRequiredForModel": true,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|womensBras",
            "DroppedTimestamp": "2022-08-24T11:57:41.546Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.683Z",
            "IssuedDate": "2022-04-21T20:28:41.811061+02:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:46.339Z",
            "UpdatedAt": "2022-08-24T12:01:02.683Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": true,
            "Gtin": "4009602833371",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 125,
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:46.359Z",
            "FMARequestID": "20220806_8REBOU",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "ConsumptionTopic": "400023",
            "ScannedAt": "2022-08-24T11:57:41.896Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "BH's",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": true,
            "LatestTimestampUpdateType": "Dropped",
            "KSUID": "2DSdaviokkxyLUhX74NKXiKupkK",
            "InboundTimestamp": "2022-08-24T11:51:19.805Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "IsRequiredForModel": true,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|womensBras",
            "DroppedTimestamp": "2022-08-24T11:56:06.218Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.702Z",
            "IssuedDate": "2022-04-21T20:32:10.873313+02:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:46.357Z",
            "UpdatedAt": "2022-08-24T12:01:02.702Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": true,
            "Gtin": "4009602833814",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 125,
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:46.404Z",
            "FMARequestID": "20220726_WYR49U",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "ConsumptionTopic": "400023",
            "ScannedAt": "2022-08-24T11:56:06.643Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "D-Shorty",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": true,
            "LatestTimestampUpdateType": "Dropped",
            "KSUID": "2DSdaqVwzSFpNOGDgZ9hZeGrvhr",
            "InboundTimestamp": "2022-08-24T11:47:45.884Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "IsRequiredForModel": true,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|womensPyjamas",
            "DroppedTimestamp": "2022-08-24T11:59:22.356Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.740Z",
            "IssuedDate": "2022-03-25T09:13:33.750645+01:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:45.459Z",
            "UpdatedAt": "2022-08-24T12:01:02.740Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": true,
            "Gtin": "7613381287453",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 120,
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:45.466Z",
            "FMARequestID": "20220806_F1N7OI",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "ConsumptionTopic": "400020",
            "ScannedAt": "2022-08-24T11:59:22.745Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "D-Slips",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": false,
            "LatestTimestampUpdateType": "Dropped",
            "Size": "38",
            "KSUID": "2DSdaoXxI41aE4iChg538MBU0h1",
            "InboundTimestamp": "2022-08-24T11:52:09.213Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "TargetGroup": "Damen",
            "IsRequiredForModel": true,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|womensSlips",
            "DroppedTimestamp": "2022-08-24T11:54:57.920Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.759Z",
            "IssuedDate": "2022-06-09T00:05:20.151845+02:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:45.677Z",
            "UpdatedAt": "2022-08-24T12:01:02.759Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": true,
            "Gtin": "4066359271160",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 145,
            "Title": "String, Microfaser, für Damen ",
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:45.722Z",
            "FMARequestID": "20220714_QGU372",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "Description": "* Microfaser mit Pünktchemuster\n* Mesh-Einsatz entlang des Bündchens",
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "BrandName": "Esprit",
            "ConsumptionTopic": "400024",
            "Color": "E380 AQUA GREEN",
            "ScannedAt": "2022-08-24T11:54:58.643Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "Mix + Match",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": true,
            "LatestTimestampUpdateType": "Dropped",
            "Size": "M",
            "KSUID": "2DSdanyzQzqqW2NtVDIRcy7Pjn9",
            "InboundTimestamp": "2022-08-24T11:48:36.283Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "TargetGroup": "Damen",
            "IsRequiredForModel": true,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|womensPyjamas",
            "DroppedTimestamp": "2022-08-24T11:58:21.274Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.762Z",
            "IssuedDate": "2022-03-25T09:11:33.993051+01:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:45.477Z",
            "UpdatedAt": "2022-08-24T12:01:02.779Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": true,
            "Gtin": "4009602858923",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 130,
            "Title": "17438 Shirt 3/4 sleeve, 197  LILAC, M",
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:45.484Z",
            "FMARequestID": "20220811_432BIY",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "BrandName": "Mey",
            "ConsumptionTopic": "400020",
            "Color": "197 LILAC",
            "ScannedAt": "2022-08-24T11:58:21.694Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "BH's",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": false,
            "LatestTimestampUpdateType": "Dropped",
            "Size": "75B",
            "KSUID": "2DSdanLCrV2zlEr38iX3iOhlZgN",
            "InboundTimestamp": "2022-08-24T11:52:31.577Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "TargetGroup": "Damen",
            "IsRequiredForModel": true,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|womensBras",
            "DroppedTimestamp": "2022-08-24T11:54:24.167Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.782Z",
            "IssuedDate": "2022-06-08T18:36:38.705735+02:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:45.657Z",
            "UpdatedAt": "2022-08-24T12:01:02.799Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": true,
            "Gtin": "4066359268696",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 145,
            "Title": "Bügel-BH, Punkte, für Damen",
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:45.716Z",
            "FMARequestID": "20220714_AR88EZ",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "Description": "* Microfaser mit Pünktchemuster\n* Mesh-Einsatz entlang des Dekolletees\n* Geraffte Träger, in der Länge verstellbar\n* Variabler Häkchenverschluss am Rücken\n* Wattierte Bügel-Cups",
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "BrandName": "Esprit",
            "ConsumptionTopic": "400024",
            "Color": "E380 AQUA GREEN",
            "ScannedAt": "2022-08-24T11:54:26.203Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "D-Slips",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": true,
            "LatestTimestampUpdateType": "Dropped",
            "Size": "L",
            "KSUID": "2DSdanAvqbgezqe4c04kGhL3UZJ",
            "InboundTimestamp": "2022-08-24T11:51:59.552Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "TargetGroup": "Damen",
            "IsRequiredForModel": true,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|womensSlips",
            "DroppedTimestamp": "2022-08-24T11:55:12.397Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.820Z",
            "IssuedDate": "2022-02-03T21:19:17.451090+01:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:45.696Z",
            "UpdatedAt": "2022-08-24T12:01:02.820Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": true,
            "Gtin": "8719851892703",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 140,
            "Title": "000QF5610E THONG CK NOS, 001 BLACK, L",
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:45.720Z",
            "FMARequestID": "20220706_FPZQ8J",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "BrandName": "CalvinKlein",
            "ConsumptionTopic": "400024",
            "Color": "001 BLACK",
            "ScannedAt": "2022-08-24T11:55:12.886Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "D-Slips",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": false,
            "LatestTimestampUpdateType": "Dropped",
            "Size": "38",
            "KSUID": "2DSdalWeRMOzkTDdgw5JAK0NPX4",
            "InboundTimestamp": "2022-08-24T11:51:30.412Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "TargetGroup": "Damen",
            "IsRequiredForModel": true,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|womensSlips",
            "DroppedTimestamp": "2022-08-24T11:55:52.438Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.842Z",
            "IssuedDate": "2022-02-03T23:30:57.668539+01:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:44.776Z",
            "UpdatedAt": "2022-08-24T12:01:02.842Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": true,
            "Gtin": "5414787197924",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 190,
            "Title": "Jane String, florale Spitze, für Damen",
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:44.788Z",
            "FMARequestID": "20220706_PPBR4O",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "BrandName": "MarieJo",
            "ConsumptionTopic": "400023",
            "Color": "schwarz",
            "ScannedAt": "2022-08-24T11:55:52.996Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "BH's",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": false,
            "LatestTimestampUpdateType": "Dropped",
            "Size": "75B",
            "KSUID": "2DSdalJGQTxSIrszxvdyCht5NpT",
            "InboundTimestamp": "2022-08-24T11:50:19.704Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "TargetGroup": "Damen",
            "IsRequiredForModel": true,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|womensBras",
            "DroppedTimestamp": "2022-08-24T11:56:36.064Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.861Z",
            "IssuedDate": "2022-05-23T13:19:37.406139+02:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:43.916Z",
            "UpdatedAt": "2022-08-24T12:01:02.861Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": true,
            "Gtin": "4066359274796",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 190,
            "Title": "Shiny Micro Fashion Bügel-BH, für Damen",
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:44.000Z",
            "FMARequestID": "20220714_9DAMHQ",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "Description": "* Wattierte Bügel-Cups\n* Längenverstellbare Träger\n* Verstellbarer Häkchenverschluss hinten",
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "BrandName": "Esprit",
            "ConsumptionTopic": "400024",
            "Color": "E325 PISTACHIO GR",
            "ScannedAt": "2022-08-24T11:56:36.555Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "Mix + Match",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": true,
            "LatestTimestampUpdateType": "Dropped",
            "KSUID": "2DSdaktretJhNBNRQslX64lT5Zr",
            "InboundTimestamp": "2022-08-24T11:48:50.385Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "IsRequiredForModel": false,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|unclassified",
            "DroppedTimestamp": "2022-08-24T11:57:55.660Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.880Z",
            "IssuedDate": "2022-03-25T09:11:34.346655+01:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:44.736Z",
            "UpdatedAt": "2022-08-24T12:01:02.880Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": false,
            "Gtin": "4009602859067",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 110,
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:44.785Z",
            "FMARequestID": "20220810_GDXOPT",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "ConsumptionTopic": "400020",
            "ScannedAt": "2022-08-24T11:57:55.923Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "BH's",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": true,
            "LatestTimestampUpdateType": "Dropped",
            "KSUID": "2DSdakXNlZGdZSoMk6YPXsATRVR",
            "InboundTimestamp": "2022-08-24T11:51:08.713Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "IsRequiredForModel": true,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|womensBras",
            "DroppedTimestamp": "2022-08-24T11:56:21.469Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.903Z",
            "IssuedDate": "2022-04-21T20:28:22.763402+02:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:44.704Z",
            "UpdatedAt": "2022-08-24T12:01:02.903Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": true,
            "Gtin": "4009602835542",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 125,
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:44.739Z",
            "FMARequestID": "20220810_HCABHW",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "ConsumptionTopic": "400023",
            "ScannedAt": "2022-08-24T11:56:22.068Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "BH's",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": false,
            "LatestTimestampUpdateType": "Dropped",
            "Size": "75B",
            "KSUID": "2DSdahvGdNCJMzeCJWPcIgIPzKa",
            "InboundTimestamp": "2022-08-24T11:51:39.161Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "TargetGroup": "Damen",
            "IsRequiredForModel": true,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|womensBras",
            "DroppedTimestamp": "2022-08-24T11:55:38.554Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.940Z",
            "IssuedDate": "2022-06-08T18:39:12.888128+02:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:44.717Z",
            "UpdatedAt": "2022-08-24T12:01:02.940Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": true,
            "Gtin": "4066359270019",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 145,
            "Title": "DELUSTER PRINT MICRO Minimizer-BH, bügellos, für Damen",
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:44.783Z",
            "FMARequestID": "20220714_EBWI9X",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "Description": "* Microfaser mit Pünktchemuster\n* Mesh-Einsatz entlang des Dekolletees\n* Wattierte, bügellose Cups\n* Geraffte Träger, in der Länge verstellbar\n* Variabler Häkchenverschluss am Rücken",
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "BrandName": "Esprit",
            "ConsumptionTopic": "400024",
            "Color": "E380 AQUA GREEN",
            "ScannedAt": "2022-08-24T11:55:39.047Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "Miederslip",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": true,
            "LatestTimestampUpdateType": "Dropped",
            "Size": "38",
            "KSUID": "2DSdagDD6zcatQ8iQhtuuFiM0oJ",
            "InboundTimestamp": "2022-08-24T11:49:06.191Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "TargetGroup": "Damen",
            "IsRequiredForModel": true,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|womensSlips",
            "DroppedTimestamp": "2022-08-24T11:57:29.094Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.961Z",
            "IssuedDate": "2022-04-21T20:27:56.541006+02:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:44.697Z",
            "UpdatedAt": "2022-08-24T12:01:02.961Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": true,
            "Gtin": "4009602836525",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 130,
            "Title": "79238 Hipster, 98  RED PEPPER, 38",
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:44.719Z",
            "FMARequestID": "20220806_U6QYQ7",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "BrandName": "Mey",
            "ConsumptionTopic": "400023",
            "Color": "98 RED PEPPER",
            "ScannedAt": "2022-08-24T11:57:29.504Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "Miederslip",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": true,
            "LatestTimestampUpdateType": "Dropped",
            "KSUID": "2DSdabsY5229wJUcfIHx0ShfA6J",
            "InboundTimestamp": "2022-08-24T11:49:34.274Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "IsRequiredForModel": false,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|unclassified",
            "DroppedTimestamp": "2022-08-24T11:57:16.046Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.963Z",
            "IssuedDate": "2022-04-21T20:27:54.572830+02:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:43.912Z",
            "UpdatedAt": "2022-08-24T12:01:02.963Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": false,
            "Gtin": "4009602836327",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 110,
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:43.977Z",
            "FMARequestID": "20220806_HPEHG2",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "ConsumptionTopic": "400023",
            "ScannedAt": "2022-08-24T11:57:16.356Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "D-Slips",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": false,
            "LatestTimestampUpdateType": "Dropped",
            "Size": "M",
            "KSUID": "2DSdaYCj3tbXZChQBYRVzqOCoC9",
            "InboundTimestamp": "2022-08-24T11:52:23.131Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "TargetGroup": "Damen",
            "IsRequiredForModel": true,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "clothingAndAccessories|womensFashion|womensSlips",
            "DroppedTimestamp": "2022-08-24T11:54:39.641Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.965Z",
            "IssuedDate": "2022-02-03T22:38:11.417637+01:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-17T00:34:43.888Z",
            "UpdatedAt": "2022-08-24T12:01:02.965Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": true,
            "Gtin": "8719851892635",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 190,
            "Title": "Slip, nahtlose Säume, unifarben, für Damen",
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-17T00:34:43.895Z",
            "FMARequestID": "20220706_IP8RFQ",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "Description": "Alles, was perfekte Unterwäsche braucht: Mit diesem Slip im Uni-Look erhalten Damen angenehmen Tragekomfort und ein ansprechendes Design. Stilvoll gekleidet mit Calvin Klein – auch auf der Ebene, die der Haut am nächsten ist.",
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "BrandName": "CalvinKlein",
            "ConsumptionTopic": "400024",
            "Color": "beige",
            "ScannedAt": "2022-08-24T11:54:40.315Z"
        },
        {
            "PhotostudioAddress": "Fotostudio Vogelheim",
            "Stage": 1004,
            "ProductGroup": "Plüschtiere, -fig.",
            "ReasonWhyInDe": "NO_REASON",
            "PhotostudioName": "Fotostudio Vogelheim",
            "IsRequiredAuxImage": false,
            "LatestTimestampUpdateType": "Dropped",
            "KSUID": "2CxZCUbIOXhVVPjOHfuEpLSnlQH",
            "InboundTimestamp": "2022-08-24T11:46:39.087Z",
            "PreviouslyContainerId": "27amOyajLurH8x5cZbyvPb86hGB",
            "ReturnCenterID": "0979000",
            "ReturnCenterAddress": "FIEGE Essen GmbH & Co. KG\nRetoure Fotostudio, H2 E1 Herr Baransky\nHafenstr. . 70 \n 45356 Essen",
            "TargetGroup": "Jungen und Mädchen",
            "IsRequiredForModel": false,
            "REPLICATION_PHOTOSTUDIO_UID": "0979000",
            "Classification": "toysAndGames|dollsPuppetsAndCuddlyToys|plushToys",
            "DroppedTimestamp": "2022-08-24T12:00:17.231Z",
            "OutboundTimestamp": "2022-08-24T12:01:02.966Z",
            "IssuedDate": "2022-02-04T01:27:35.030020+01:00",
            "ReturnCenterName": "Retourenbetrieb Vogelheim",
            "IsFullFilledRequiredImages": false,
            "TransportUnitId": "2DnjxnZg3CC626YLwlnLqoWcWPu",
            "IsoTimeBased": "2022-08-06T00:34:28.448Z",
            "UpdatedAt": "2022-08-24T12:01:02.966Z",
            "ContainerId": "DROPPED_OR_END_OF_ARTICLE_LIFE_CYCLE",
            "FetchedStyleGuide": false,
            "Gtin": "4004510906827",
            "ShootingMode": 1003,
            "TotalAuxImage": 0,
            "IsFullFilledMandatoryAuxImage": false,
            "PhotostudioID": "0979000",
            "Status": 145,
            "Title": "Kuscheltier Katze, 20 cm",
            "DropReasonID": "NO_DROP_ID",
            "CreatedAt": "2022-08-06T00:34:28.481Z",
            "FMARequestID": "20220805_1HFNJT",
            "Channel": "gkkDigitalDataManagement",
            "AdvertisingPlanId": null,
            "Description": "Der niedliche Haustiger aus der Hermann Teddy Collection ist aus hochwertigem rot-getigertem Plüsch gefertigt und mit softer Polyesterwatte gefüllt. Die Katze steht auf 4 Pfoten für optimale Bespielbarkeit und wurde vom Arbeitsausschuss Kinderspiel + Spielzeug e.V. mit spiel gut ausgezeichnet. Vom TÜV Rheinland wurde die Katze getestet und mit tuv.com zertifiziert. Teddy Hermann ist ein Familienunternehmen aus Bayern, das bereits seit über 100 Jahren Kinder und Eltern gleichermaßen mit flauschigen Plüschspieltieren entzückt. Das rote Teddy-Siegel von Teddy Hermann steht für Premium Qualität, Wertigkeit und geprüfte Produktsicherheit. Besonders bekannt und beliebt ist Teddy Hermann für seine naturnah gestalteten kuscheligen Plüschspieltieren mit Niedlichkeitsfaktor. Der Mix aus liebevollem Design, besonderen Details und treuherzigem Gesichtsausdruck macht jedes Tier und jeden Teddy zum Liebhaberstück.",
            "State": "ACTIVE",
            "LifeCycleStage": 1002,
            "TotalRequiredImage": 0,
            "CalenderWeek": null,
            "GoodsType": null,
            "ReasonWhyInEng": "NO_REASON",
            "BrandName": "TeddyHermann",
            "ConsumptionTopic": "400068",
            "Color": "ROT",
            "ScannedAt": "2022-08-24T12:00:17.509Z"
        }
    ]
}

const transportUnitData = {
    fmaRequestId: '1HTE4TDFGEFEF2D',
    goodsType: 'ADVERTISING',
    senderLocation: {
        id: '0304000',
        type: 'HEADQUATER',
        displayName: 'My Studio',
        address1: 'My Studio Bmbh',
        address2: 'ABC department',
        street: 'Orange str',
        houseNumber: '21',
        zipCode: '123454',
        city: 'Vogelheim',
        email: 'abc@abc.com',
        contactPerson: 'Tom',
        startDate: '23/2/2022',
        endDate: '23/2/2022',
    },
    targetLocation: {
        id: '0979000',
        type: 'PHOTOSTUDIO',
        displayName: 'ABC PhotoStudio',
        address1: 'ABC Studio Bmbh',
        address2: null,
        street: 'Orange str',
        houseNumber: '21',
        zipCode: '123454',
        city: 'Essen',
        email: 'abc@abc.com',
        contactPerson: 'Tom',
        startDate: '23/2/2022',
        endDate: '23/2/2022',
    },
    packedBy: 'abc@gmail.com',
    articles: [
        { gtin:'1234567801234', title:'Product 1', advertisingPlanId: "2022-000019", calendarWeek: "19/2019"},
        { gtin:'8763251359235', title:'Product 2', advertisingPlanId: "2022-000019", calendarWeek: "19/2019" },
    ]
}

//let docDefinition = getOrderTemplateDocDefinition(transportUnitData);
let docDefinition = getTemplateDocDefinition(transportUnit, articles);
pdfMake.vfs = pdfFonts.pdfMake.vfs;

pdfMake.fonts = {
    Roboto: {
        normal: 'Roboto-Regular.ttf',
        bold: 'Roboto-Medium.ttf',
    }
}

let fileName = 'basics.pdf'
let pdf = pdfMake.createPdf(docDefinition, undefined)

//1. if we want to save to file, use lines below
import fs from 'fs';
/*
pdf.getBase64((data) => {
    fs.writeFile(fileName, data, { encoding: 'base64'}, error => { })
    console.log('test file has been generated');
});
*/

pdf.getBuffer((buffer)=>{
    fs.writeFile(fileName, buffer, error => { if(error) console.log(error)})
    console.log('file has been generated');
});

/*
2. we want to save to s3, use lines below

import awss3 from 'aws-sdk/clients/s3';
import stream from 'stream';

function getS3OutputStream(bucket: string, key: string) {
    var passthroughStream = new stream.PassThrough();
    var params:awss3.PutObjectRequest = {
        Bucket: bucket, 
        Key: key, 
        Body: passthroughStream};
        
    let s3 = new awss3();
    s3.upload(params, function(err, data){ 
        if(err){
            console.log('!!! ERROR !!!');
            console.log(err, data);            
        }
        else{
            console.log(data);
        }
    });
  
    return passthroughStream;
}

const bucket = 'arn:aws:s3:eu-central-1:085420227850:accesspoint/vuleaccesspoint'
const awsFileName = `pdfs/file-${Date.now()}.pdf`
let s3OutputStream = getS3OutputStream(bucket, awsFileName);
var pdfStream = pdf.getStream()
pdfStream.pipe(s3OutputStream);
pdfStream.end();
*/